---
volumes:
  postgres_data:
    driver: local
  caddy_data:
    driver: local

services:
  postgres:
    container_name: postgres-keycloak
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    container_name: managed-keycloak
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_FEATURES: persistent-user-sessions
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_MANAGEMENT_PORT: 9000
      KC_LOG_LEVEL: "INFO,io.phasetwo:DEBUG"
      KC_METRICS_ENABLED: true
      KC_PROXY: 'edge'
      KC_TRANSACTION_JTA_ENABLED: 'false'
      KC_TRANSACTION_XA_ENABLED: 'false'

    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--spi-email-template-provider=freemarker-plus-mustache", "--spi-email-template-freemarker-plus-mustache-enabled=true", "--spi-theme-cache-themes=false"]
    ports:
      - 9000:9000
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
  caddy:
    container_name: caddy-keycloak
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://localhost:443 --to http://keycloak:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
    depends_on:
      - keycloak
